#MicroService Id
spring.application.name=orders-service



#Jpa Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

#Server Configuration
server.port=8005
server.servlet.context-path=/orders

#DevTools Configuration
spring.devtools.restart.enabled=true

#EurekaServiceUrl
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

#EnableIpAddress
eureka.instance.prefer-ip-address=true