#MicroService Id
spring.application.name=orders-service


#Server Configuration
server.port=8005
server.servlet.context-path=/orders

#DevTools Configuration
spring.devtools.restart.enabled=true

#EurekaServiceUrl
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

#ConfigServerUrl
spring.config.import=optional:configserver:http://localhost:9988/config

#Instead of hostname look for ipAddr
eureka.instance.prefer-ip-address=true

spring.jpa.show-sql=false